
######################## STARTING QUICK SCAN AUTONOMY ########################
Starting Quickscan CV
Received data from comms simulation: {u'missionInfo': {u'searchArea': {u'topLeft': [15.328375, -100.752615], u'bottomLeft': [15.328375, -140.752615], u'topRight': [55.328375, -100.752615], u'bottomRight': [55.328375, -140.752615]}}, u'type': u'addMission', u'id': 0}
Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Users\Terry H\Documents\GitHub\VTOL\autonomy.py", line 263, in comm_simulation
    xbee_callback(DummyMessage(json.dumps(instr["message"])), autonomyToCV)
  File "C:\Users\Terry H\Documents\GitHub\VTOL\quick_scan_autonomy.py", line 55, in xbee_callback
    area["bottomLeft"], area["bottomRight"])
  File "C:\Users\Terry H\Documents\GitHub\VTOL\quick_scan_autonomy.py", line 24, in __init__
    self.tl = (bytes.fromhex(tl[0]), bytes.fromhex(tl[1]))
AttributeError: type object 'str' has no attribute 'fromhex'

